### PR TITLE
Add ExternalMemorySortManager and MateVectorByRN

### PR DESCRIPTION
**Pull request by pjvandehaar**
A copy of https://github.com/statgen/gotcloud/pull/23 with a few further changes

### CODE REVIEW

**Comment by pjvandehaar** [comment]
@Griffan If you want to make more changes, you can clone this repo and checkout this branch (see _command line instructions_ just above this comment).

It's a neat trick that instead of `#include "Bam2FastQ.h"` you can just do `class Bam2FastQ;`.  I think I'll start using that.  But, will it lead to suffering later?

**Comment by Griffan** [comment]
@pjvandehaar 
Thank you!
The `class Bam2FastQ;` is for the "cross reference", because otherwise both of the two headers will include each other and result in bad result. I'd suggest you to stick with the conventional way, use it when only it's necessary.

**Comment by pjvandehaar** [comment]
@Griffan Got it, thanks for explaining that.

@mktrost Is there anything else I should do here?

**Comment by Griffan** [comment]
@pjvandehaar 
Because `Bam2FastQ` doesn't manipulate `MateVectorByRN` directly.

**Comment by mktrost** [comment]
Great, I'm glad to see multithreading coming into bamUtil.  
I believe this is to multi-thread to sort by readname on the fly.
I might offer some suggestions (maybe for future versions):
1) this could potentially be a useful feature that could be used by other tools, not just bam2fastq.
Maybe there could be a base class setup to take advantage of that so other tools could take advantage of this too.  
2) Is it necessary to make all of bam2fastq public?  Maybe some reworking on the classes would resolve it so that it wouldn't all have to be public.  Maybe some logic/variables could be transferred to more appropriate classes, so less needs to be public (I haven't really looked too well).  I understand this is probably the easiest/quickest solution and since Bam2FastQ isn't really included by many classes, it probably isn't a problem, but it is something to think about.  This may come more into play if we have other classes sort on the fly too and share the threading/sorting code.

**Comment by Griffan** [comment]
@mktrost 
1) yes, I think so, but since this is just a quick and dirty version. We need to do some work on abstraction.

2）No,  it's definitely not. I will try to rearrange these variables.

**Comment by mktrost** [comment]
Makes sense, sometimes you have to make quick and dirty changes (I did that
with the low memory deduper). Thanks for adding this capability.

**Comment by pjvandehaar** [comment]
Closed in favor of a new branch.

**Pull request closed without merging**
